{{- if eq .Values.hostScanner.enable true }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qualys-clustersensor-rb
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/resource-policy: keep
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: qualys-clustersensor-role
subjects:
- kind: ServiceAccount
  name: qualys-clustersensor-sa
  namespace: {{ .Release.Namespace }}
{{- end }}