
{{- if and .Values.global .Values.global.rootCA.certificate }}
apiVersion: v1
kind: Secret
metadata:
  name: root-ca-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  custom-root-ca.crt: {{ .Values.global.rootCA.certificate }}
{{- end }}

---
{{- if and .Values.global .Values.global.proxy.certificate }}
apiVersion: v1
kind: Secret
metadata:
  name: proxy-ca-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  custom-proxy-ca.crt: {{ .Values.global.proxy.certificate }}
{{- end }}