# RoleBinding to assign permissions in qualys-reader-role to qualys-service-account

{{-  if (semverCompare "<=1.17-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
{{- end }}
kind: RoleBinding
metadata:
  name: qualys-reader-rb
{{- if .Values.qualys.namespace }}
  namespace: {{.Values.qualys.namespace}}
{{- else }}
  namespace: {{ .Release.Namespace }}
{{- end }}
subjects:
  - kind: ServiceAccount
    name: qualys-service-account
{{- if .Values.qualys.namespace }}
    namespace: {{.Values.qualys.namespace}}
{{- else }}
    namespace: {{ .Release.Namespace }}
{{- end }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: qualys-reader-role
