# Secret

{{- if .Values.containerd.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: containerd-cert-config
  namespace: qualys
data:
  ca.crt: # Paste base 64 encoded content of ca.crt file
{{- end }}
