# Role for all permission to qualys namespace

{{- if (semverCompare "<=1.17-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
{{- end }}
kind: Role
metadata:
  name: qualys-reader-role
{{- if .Values.qualys.namespace }}
  namespace: {{.Values.qualys.namespace}}
{{- else }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- if .Values.crio.enabled }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["create", "delete", "deletecollection"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get","create", "delete", "deletecollection"]
  - apiGroups: [""]
    resources: ["pods/attach"]
    verbs: ["create"]
{{- else if .Values.docker.enabled }}
rules:
  - apiGroups: ["","batch"]
    resources: ["pods","jobs"]
    verbs: ["get", "list", "watch","create", "delete", "deletecollection"]
  - apiGroups: [""]
    resources: ["pods/status"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods/attach", "pods/exec"]
    verbs: ["create"]
{{- else }}
rules:
  - apiGroups: ["","batch"]
    resources: ["pods","jobs"]
    verbs: ["get", "list", "watch","create", "delete", "deletecollection"]
  - apiGroups: [""]
    resources: ["pods/attach", "pods/exec"]
    verbs: ["create"]
{{- end }}
