# ClusterRole for read permission to whole cluster

{{-  if (semverCompare "<=1.17-0" (substr 1 -1 .Capabilities.KubeVersion.GitVersion)) }}
apiVersion: rbac.authorization.k8s.io/v1beta1
{{- else }}
apiVersion: rbac.authorization.k8s.io/v1
{{- end }}
kind: ClusterRole
metadata:
  name: qualys-cluster-reader-role
{{- if .Values.crio.enabled }}
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods/status", "replicationcontrollers/status", "nodes/status", "namespaces"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get","list","watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: ["apps"]
    resources: ["replicasets/status", "daemonsets/status", "deployments/status", "statefulsets/status"]
    verbs: ["get"]
  - apiGroups: ["batch"]
    resources: ["jobs/status", "cronjobs/status"]
    verbs: ["get"]
{{- else if .Values.docker.enabled }}
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods/status", "replicationcontrollers/status", "nodes/status", "namespaces"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["replicasets/status", "daemonsets/status", "deployments/status", "statefulsets/status"]
    verbs: ["get"]
  - apiGroups: ["batch"]
    resources: ["jobs/status", "cronjobs/status"]
    verbs: ["get"]
{{- else }}
rules:
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["nodes", "pods", "pods/status", "replicationcontrollers/status", "nodes/status", "namespaces"]
    verbs: ["get"]
  - apiGroups: ["apps"]
    resources: ["replicasets/status", "daemonsets/status", "deployments/status", "statefulsets/status"]
    verbs: ["get"]
  - apiGroups: ["batch"]
    resources: ["jobs/status", "cronjobs/status"]
    verbs: ["get"]
{{- end }}
