{{- $providerName := include "lxagent.providerName" . }}
{{- if eq $providerName "COREOS" }}
# RoleBinding 'qualys-agent-rolebinding' to bind Role 'qualys-agent-role' to Service Account 'qualys-agent-sa'
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: qualys-agent-rolebinding
  namespace: {{ .Values.qualys.namespace }}
subjects:
  - kind: ServiceAccount
    name: qualys-agent-sa
    namespace: {{ .Values.qualys.namespace }}  # Corrected to use namespace from values.yaml
roleRef:
  kind: Role
  name: qualys-agent-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}
