{{- if eq .Values.qualys.args.providerName "COREOS" }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: qualys-agent-anyuid-binding
subjects:
  - kind: ServiceAccount
    name: qualys-agent-sa
    namespace: {{ .Values.qualys.namespace }}
roleRef:
  kind: ClusterRole
  name: hostmount-anyuid
  apiGroup: rbac.authorization.k8s.io
{{- end }}
