{{- $providerName := include "lxagent.providerName" . }}
{{- if eq $providerName "COREOS" }}
# ServiceAccount 'qualys-agent-sa'
apiVersion: v1
kind: ServiceAccount
metadata:
  name: qualys-agent-sa
  namespace: {{ .Values.qualys.namespace }}
{{- end }}
