kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name:  qualys-runtime-sensor-cluster-role
rules:
  - apiGroups: ["apiextensions.k8s.io"]
    verbs: ["get","list","watch"]
    resources: ["customresourcedefinitions"]
  - apiGroups: [""]
    resources: ["pods","services","nodes","namespaces"]
    verbs: ["get","list","watch"]
  - apiGroups: ["cilium.io"]
    resources: ["tracingpolicies","tracingpoliciesnamespaced"]
    verbs: ["get","list","watch"]
  - apiGroups: ["qualys.com"]
    resources: ["policies"]
    verbs: ["get","list","watch"]
  - apiGroups: ["qualys.com"]
    resources: ["runtimepolicies"]
    verbs: ["get","list","watch"]