# OpenShift

{{- if .Values.global.openshift }}
kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: scc-qualys-runtimesensor-sa
allowHostDirVolumePlugin: true
allowHostNetwork: true
allowHostIPC: false
allowHostPID: false
allowHostPorts: false
allowPrivilegedContainer: true
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
users:
- {{printf "system:serviceaccount:%s:qualys-runtimesensor-sa" .Release.Namespace }}
{{- end }}
