image: "qualys/runtime-sensor:1.3.0-0" 
imagePullPolicy:  "Always"
logConfig:
  logLevel: "info" #valid values of loglevel(debug, info, error, warn, fatal)
  logFileSize: 10 #logFileSize is in MegaBytes(MB) 
  logPurgeCount: 5
hostNetwork: true
# Set true to allow sensor to mount host's /proc in read-only mode
hostProc: true
# Set true to enable debug policy , false by default
enableDebugPolicy: false
ignoreProcess: "" #list of comma separated process paths, whose events are to be ignored. e.g. /usr/bin/snap
processAllowList:
  enabled: true
  value: "" #list of comma separated regexes of process binaries which need to be allowed. e.g. /*/cat , /*/(curl|cat)
resources:
  limits:
    cpu: "800m"
    memory: "1024Mi"
  requests:
    cpu: "500m"
    memory: "1024Mi"
persistentStorage:
  enabled: false
  hostPath: "/usr/local/qualys/runtime-sensor/data"

# Set tolerations here
tolerations:

# add nodeselector here
nodeSelector:

# set nodeAffinity,podAffinity under affinity
affinity:

