apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "admission-controller.fullname" . }}
rules:
  - apiGroups: ["cs.qualys.com"]
    resources: [{{ include "admission-controller.fullname" . }}]
    verbs: [ "get", "list", "watch", "create" ]
  - apiGroups: [ "" ]
    resources: [ "namespaces" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "" ]
    resources: [ "nodes" ]
    verbs: [ "get", "list" ]