apiVersion: v1
kind: Service
metadata:
  name: admission-controller
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      targetPort: {{ .Values.port }}
  selector:
    app: admission-controller